In [8]:
import pandas as pd
import glob
import datetime
from dateutil.relativedelta import relativedelta

In [19]:
path=[]
for file in glob.glob('/Users/chenjessie/Desktop/經濟預測模型/data/*.csv'):
    path.append(file)
    print(file)

/Users/chenjessie/Desktop/經濟預測模型/data/CPI.csv
/Users/chenjessie/Desktop/經濟預測模型/data/新屋銷售.csv
/Users/chenjessie/Desktop/經濟預測模型/data/新屋開工.csv
/Users/chenjessie/Desktop/經濟預測模型/data/成屋銷售.csv
/Users/chenjessie/Desktop/經濟預測模型/data/信心.csv
/Users/chenjessie/Desktop/經濟預測模型/data/個人支出.csv
/Users/chenjessie/Desktop/經濟預測模型/data/coreCPI.csv
/Users/chenjessie/Desktop/經濟預測模型/data/失業率.csv
/Users/chenjessie/Desktop/經濟預測模型/data/GDP.csv

In [20]:
df1 = pd.read_csv(path[1])
df2 = pd.read_csv(path[2])
df3 = pd.read_csv(path[3])
df4 = pd.read_csv(path[0])
df5 = pd.read_csv(path[6])
df6 = pd.read_csv(path[5])
df7 = pd.read_csv(path[4])
df8 = pd.read_csv(path[7])
df9 = pd.read_csv(path[8])

In [21]:
df = pd.merge(df1,df2, on='日期',how='outer')
df

             日期  新屋銷售   新屋開工
0    2020-04-01  62.7  121.6
1    2020-03-01  76.5  159.9
2    2020-02-01  76.4  156.7
3    2020-01-01  69.4  160.8
4    2019-12-01  71.9  136.5
..          ...   ...    ...
599  1970-05-01  44.5  126.0
600  1970-04-01  38.9  132.0
601  1970-03-01  37.3  131.0
602  1970-02-01  46.1  109.0
603  1970-01-01  45.2  133.0

[604 rows x 3 columns]

In [36]:

df = pd.merge(df,df9, on='日期',how='outer')
df

,日期,新屋銷售,新屋開工,成屋銷售,CPI,coreCPI,個人支出,信心,失業率,Unnamed: 0,GDP
0,2020-04-01,62.7,121.6,527,-0.4,-0.1,-7.5,71.800000,4.4,0,-4.80000
1,2020-03-01,76.5,159.9,577,0.1,0.2,0.2,89.100000,3.5,1,2.10000
2,2020-02-01,76.4,156.7,546,0.1,0.2,0.2,101.000000,3.6,2,2.10000
3,2020-01-01,69.4,160.8,554,0.2,0.1,0.3,99.800000,3.5,3,2.10000
4,2019-12-01,71.9,136.5,535,0.3,0.2,0.4,99.300000,3.5,4,2.10000
...,...,...,...,...,...,...,...,...,...,...,...
599,1970-05-01,44.5,126.0,151,0.5,0.7,0.6,85.917625,4.6,452,-0.25408
600,1970-04-01,38.9,132.0,137,0.5,0.8,-0.3,85.917625,4.4,453,-0.25408
601,1970-03-01,37.3,131.0,146,0.5,0.5,0.8,78.100000,4.2,454,-0.25408
602,1970-02-01,46.1,109.0,153,0.5,0.5,1.0,85.917625,3.9,455,-0.25408
603,1970-01-01,45.2,133.0,160,0.5,0.5,0.4,85.917625,3.5,456,-0.25408

In [39]:
df=df.drop(columns=['Unnamed: 0'])

In [40]:
df

,日期,新屋銷售,新屋開工,成屋銷售,CPI,coreCPI,個人支出,信心,失業率,GDP
0,2020-04-01,62.7,121.6,527,-0.4,-0.1,-7.5,71.800000,4.4,-4.80000
1,2020-03-01,76.5,159.9,577,0.1,0.2,0.2,89.100000,3.5,2.10000
2,2020-02-01,76.4,156.7,546,0.1,0.2,0.2,101.000000,3.6,2.10000
3,2020-01-01,69.4,160.8,554,0.2,0.1,0.3,99.800000,3.5,2.10000
4,2019-12-01,71.9,136.5,535,0.3,0.2,0.4,99.300000,3.5,2.10000
...,...,...,...,...,...,...,...,...,...,...
599,1970-05-01,44.5,126.0,151,0.5,0.7,0.6,85.917625,4.6,-0.25408
600,1970-04-01,38.9,132.0,137,0.5,0.8,-0.3,85.917625,4.4,-0.25408
601,1970-03-01,37.3,131.0,146,0.5,0.5,0.8,78.100000,4.2,-0.25408
602,1970-02-01,46.1,109.0,153,0.5,0.5,1.0,85.917625,3.9,-0.25408
603,1970-01-01,45.2,133.0,160,0.5,0.5,0.4,85.917625,3.5,-0.25408

In [41]:
df.to_csv('/Users/chenjessie/Desktop/經濟預測模型/data/全部.csv', index=True)

In [5]:
df1 = pd.read_csv('/Users/chenjessie/Desktop/經濟預測模型/data/全部.csv')
df2 = pd.read_csv('/Users/chenjessie/Desktop/經濟預測模型/data/predict/predict.csv')

In [6]:
df = pd.merge(df1,df2, on='日期',how='outer')
df

,Unnamed: 0,日期,新屋銷售,新屋開工,成屋銷售,CPI,coreCPI,個人支出,信心,失業率,GDP,predict
0,0,2020-04-01,62.7,121.6,527,-0.4,-0.1,-7.5,71.800000,4.4,-4.80000,0
1,1,2020-03-01,76.5,159.9,577,0.1,0.2,0.2,89.100000,3.5,2.10000,0
2,2,2020-02-01,76.4,156.7,546,0.1,0.2,0.2,101.000000,3.6,2.10000,3
3,3,2020-01-01,69.4,160.8,554,0.2,0.1,0.3,99.800000,3.5,2.10000,1
4,4,2019-12-01,71.9,136.5,535,0.3,0.2,0.4,99.300000,3.5,2.10000,1
...,...,...,...,...,...,...,...,...,...,...,...,...
599,599,1970-05-01,44.5,126.0,151,0.5,0.7,0.6,85.917625,4.6,-0.25408,3
600,600,1970-04-01,38.9,132.0,137,0.5,0.8,-0.3,85.917625,4.4,-0.25408,2
601,601,1970-03-01,37.3,131.0,146,0.5,0.5,0.8,78.100000,4.2,-0.25408,2
602,602,1970-02-01,46.1,109.0,153,0.5,0.5,1.0,85.917625,3.9,-0.25408,1
603,603,1970-01-01,45.2,133.0,160,0.5,0.5,0.4,85.917625,3.5,-0.25408,2

In [7]:
df=df.drop(columns=['Unnamed: 0'])
df

,日期,新屋銷售,新屋開工,成屋銷售,CPI,coreCPI,個人支出,信心,失業率,GDP,predict
0,2020-04-01,62.7,121.6,527,-0.4,-0.1,-7.5,71.800000,4.4,-4.80000,0
1,2020-03-01,76.5,159.9,577,0.1,0.2,0.2,89.100000,3.5,2.10000,0
2,2020-02-01,76.4,156.7,546,0.1,0.2,0.2,101.000000,3.6,2.10000,3
3,2020-01-01,69.4,160.8,554,0.2,0.1,0.3,99.800000,3.5,2.10000,1
4,2019-12-01,71.9,136.5,535,0.3,0.2,0.4,99.300000,3.5,2.10000,1
...,...,...,...,...,...,...,...,...,...,...,...
599,1970-05-01,44.5,126.0,151,0.5,0.7,0.6,85.917625,4.6,-0.25408,3
600,1970-04-01,38.9,132.0,137,0.5,0.8,-0.3,85.917625,4.4,-0.25408,2
601,1970-03-01,37.3,131.0,146,0.5,0.5,0.8,78.100000,4.2,-0.25408,2
602,1970-02-01,46.1,109.0,153,0.5,0.5,1.0,85.917625,3.9,-0.25408,1
603,1970-01-01,45.2,133.0,160,0.5,0.5,0.4,85.917625,3.5,-0.25408,2

In [ ]:
df=df.drop(columns=['Unnamed: 0'])

In [11]:
df=df.drop(index=1)
df

,日期,新屋銷售,新屋開工,成屋銷售,CPI,coreCPI,個人支出,信心,失業率,GDP,predict
2,2020-02-01,76.4,156.7,546,0.1,0.2,0.2,101.000000,3.6,2.10000,3
3,2020-01-01,69.4,160.8,554,0.2,0.1,0.3,99.800000,3.5,2.10000,1
4,2019-12-01,71.9,136.5,535,0.3,0.2,0.4,99.300000,3.5,2.10000,1
5,2019-11-01,73.3,131.4,546,0.4,0.2,0.3,96.800000,3.6,2.10000,2
6,2019-10-01,70.1,125.6,538,0.0,0.1,0.2,95.500000,3.5,1.90000,2
...,...,...,...,...,...,...,...,...,...,...,...
599,1970-05-01,44.5,126.0,151,0.5,0.7,0.6,85.917625,4.6,-0.25408,3
600,1970-04-01,38.9,132.0,137,0.5,0.8,-0.3,85.917625,4.4,-0.25408,2
601,1970-03-01,37.3,131.0,146,0.5,0.5,0.8,78.100000,4.2,-0.25408,2
602,1970-02-01,46.1,109.0,153,0.5,0.5,1.0,85.917625,3.9,-0.25408,1
603,1970-01-01,45.2,133.0,160,0.5,0.5,0.4,85.917625,3.5,-0.25408,2

In [13]:
df = df.set_index('日期') 
df
df.to_csv('/Users/chenjessie/Desktop/經濟預測模型/data/全部.csv', index=True)