In [1]:
%matplotlib inline
import matplotlib
import matplotlib.pyplot as plt

# Dataroma

https://www.dataroma.com/m/holdings.php?m=psc

### Target

1. Track holding history automatically.

2. Grab the weights from the table, and transform it into a usable dataframe in R

In [2]:
import requests
from bs4 import BeautifulSoup
import sys
import codecs
#from selenium import webdriver
#from selenium.webdriver.support.ui import WebDriverWait
#from selenium.webdriver.common.keys import Keys
import requests
import time
from fake_useragent import UserAgent
import csv
import pandas as pd

#Use fake UserAgent
def set_header_user_agent():
    user_agent = UserAgent()
    return user_agent.random

#open browser #打開瀏覽器，但不要載入圖片
#options = webdriver.ChromeOptions()
#prefs = {
#    'profile.default_content_setting_values': {
#        'images': 2,
#        #'javascript': 2
#    }
#}
#options.add_experimental_option('prefs', prefs)

#driver = webdriver.Chrome('./chromedriver', chrome_options=options)


#define urls
url = "https://www.dataroma.com/m/hist/p_hist.php?f=psc" #holding history

user_agent = set_header_user_agent()
res = requests.get(url, headers={ 'user-agent': user_agent })
#res
soup = BeautifulSoup(res.text, 'html.parser')

### Try to crawl the whole table as a dataframe

In [3]:
table = soup.find_all('table')
df = pd.read_html(str(table))[0]
#ref: https://stackoverflow.com/questions/50633050/scrape-tables-into-dataframe-with-beautifulsoup/50633450

df.head()

,Period,Portfolio Value,Top 20 holdings history (left to right),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
0,2019 Q4,$6.55 B,CMG Chipotle Mexican Grill Inc.22.03% of portf...,HLT Hilton Worldwide Holdings17.87% of portfolio,LOW Lowe's Cos.15.74% of portfolio,QSR Restaurant Brands International14.68% of p...,BRK.B Berkshire Hathaway CL B13.88% of portfolio,SBUX Starbucks Corp.7.32% of portfolio,HHC Howard Hughes Corp.4.25% of portfolio,A Agilent Technologies4.23% of portfolio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019 Q3,$6.49 B,CMG Chipotle Mexican Grill Inc.22.33% of portf...,QSR Restaurant Brands International16.54% of p...,HLT Hilton Worldwide Holdings15.15% of portfolio,LOW Lowe's Cos.14.59% of portfolio,BRK.B Berkshire Hathaway CL B12.87% of portfolio,SBUX Starbucks Corp.12.69% of portfolio,A Agilent Technologies3.44% of portfolio,HHC Howard Hughes Corp.2.39% of portfolio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019 Q2,$6.71 B,CMG Chipotle Mexican Grill Inc.19.48% of portf...,QSR Restaurant Brands International16.21% of p...,HLT Hilton Worldwide Holdings15.98% of portfolio,LOW Lowe's Cos.13.39% of portfolio,SBUX Starbucks Corp.11.64% of portfolio,BRK.B Berkshire Hathaway CL B11.16% of portfolio,ADP Automatic Data Processing Inc.9.93% of por...,HHC Howard Hughes Corp.2.21% of portfolio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019 Q1,$6.72 B,CMG Chipotle Mexican Grill Inc.19.70% of portf...,QSR Restaurant Brands International17.78% of p...,LOW Lowe's Cos.15.18% of portfolio,HLT Hilton Worldwide Holdings13.57% of portfolio,RTX Raytheon Technologies Corp.11.17% of portf...,SBUX Starbucks Corp.11.06% of portfolio,ADP Automatic Data Processing Inc.9.58% of por...,HHC Howard Hughes Corp.1.96% of portfolio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2018 Q4,$5.96 B,QSR Restaurant Brands International17.28% of p...,LOW Lowe's Cos.14.79% of portfolio,CMG Chipotle Mexican Grill Inc.14.07% of portf...,HLT Hilton Worldwide Holdings13.19% of portfolio,SBUX Starbucks Corp.12.71% of portfolio,RTX Raytheon Technologies Corp.9.97% of portfolio,ADP Automatic Data Processing Inc.8.96% of por...,PAH Platform Specialty Products Corp.7.01% of ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

#### 可以清的方式

* 個股名稱：
用空格斷字串，第一個字串即是（前面三個字母左右）

* 個股持有比例：
用Holdings 13.19% of portfolio斷字串，中間的字串即是

In [4]:
#把period當作index
df.set_index("Period", inplace = True)
df.head()

,Portfolio Value,Top 20 holdings history (left to right),Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,...,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21
Period,,,,,,,,,,,,,,,,,,,,,
2019 Q4,$6.55 B,CMG Chipotle Mexican Grill Inc.22.03% of portf...,HLT Hilton Worldwide Holdings17.87% of portfolio,LOW Lowe's Cos.15.74% of portfolio,QSR Restaurant Brands International14.68% of p...,BRK.B Berkshire Hathaway CL B13.88% of portfolio,SBUX Starbucks Corp.7.32% of portfolio,HHC Howard Hughes Corp.4.25% of portfolio,A Agilent Technologies4.23% of portfolio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019 Q3,$6.49 B,CMG Chipotle Mexican Grill Inc.22.33% of portf...,QSR Restaurant Brands International16.54% of p...,HLT Hilton Worldwide Holdings15.15% of portfolio,LOW Lowe's Cos.14.59% of portfolio,BRK.B Berkshire Hathaway CL B12.87% of portfolio,SBUX Starbucks Corp.12.69% of portfolio,A Agilent Technologies3.44% of portfolio,HHC Howard Hughes Corp.2.39% of portfolio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019 Q2,$6.71 B,CMG Chipotle Mexican Grill Inc.19.48% of portf...,QSR Restaurant Brands International16.21% of p...,HLT Hilton Worldwide Holdings15.98% of portfolio,LOW Lowe's Cos.13.39% of portfolio,SBUX Starbucks Corp.11.64% of portfolio,BRK.B Berkshire Hathaway CL B11.16% of portfolio,ADP Automatic Data Processing Inc.9.93% of por...,HHC Howard Hughes Corp.2.21% of portfolio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019 Q1,$6.72 B,CMG Chipotle Mexican Grill Inc.19.70% of portf...,QSR Restaurant Brands International17.78% of p...,LOW Lowe's Cos.15.18% of portfolio,HLT Hilton Worldwide Holdings13.57% of portfolio,RTX Raytheon Technologies Corp.11.17% of portf...,SBUX Starbucks Corp.11.06% of portfolio,ADP Automatic Data Processing Inc.9.58% of por...,HHC Howard Hughes Corp.1.96% of portfolio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018 Q4,$5.96 B,QSR Restaurant Brands International17.28% of p...,LOW Lowe's Cos.14.79% of portfolio,CMG Chipotle Mexican Grill Inc.14.07% of portf...,HLT Hilton Worldwide Holdings13.19% of portfolio,SBUX Starbucks Corp.12.71% of portfolio,RTX Raytheon Technologies Corp.9.97% of portfolio,ADP Automatic Data Processing Inc.8.96% of por...,PAH Platform Specialty Products Corp.7.01% of ...,HHC Howard Hughes Corp.2.02% of portfolio,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
#在一個row裡取不同column的值 這裡取第2個column，所以最後的中括號是1
testrow = df.iloc[2][1]
print(testrow)

#type(df.iloc[2][1]) #是str
stock_name = testrow.split()[0] #先用空格split
print(stock_name) #拿到個股名稱

#拿個股權重
test_wei = testrow.split()[-3].split('%')
test_wei = test_wei[0][-5:]
print(test_wei)
test_wei = float(test_wei)
print(test_wei)

CMG Chipotle Mexican Grill Inc.19.48% of portfolio
CMG
19.48
19.48

In [6]:
##str 有unique嗎？
#astring = ['CMG', "CMG", "A", "HLT", "HLT"]
#pd.unique(astring) #pandas有

#先做一個有各個股票名稱作為col的array
#所以要先取出所有的個股名稱存起來在一個list裡，再取unique

stock_names = []
for i in range(0,df.shape[0]): #在row裡
    for j in range(0,df.shape[1]): #在col裡
        obs = df.iloc[i][j]       # i-th j-th obs
        try:
            stock_name = obs.split()[0] #用空格分隔後的第一個即是個股名稱
            stock_names.append(stock_name)
        except:
            continue
uni_names = pd.unique(stock_names)
uni_names.sort()
#print(uni_names)

"A" in uni_names
#uni_names.index("A")
uni_names = uni_names[uni_names>="A"]

for i in range(0, len(uni_names)):
    print(uni_names[i], end = ' ')

A ACT ADP AGN AIG AIV ALEX ALX APD BEAM BGP BHC BKS BKW-OLD BRK.B C CBY CEN CMG CP CSG CXW DPS EMC FBHS FDO FO GGP GLRE GM H HHC HLT HME JCP LDG LNY LOW MA MATX MCD MDLZ NKE NOMD PAH PG QSR RTX SBUX SHLDQ SKS SPLS TGT V WB-OLD WEN YUM ZTS

## 用一個dict來存

for every unique stock name, we have:

key : value = peroid : weight


是把dataframe裡的每列的每個cell遍歷，遇到特定的關鍵字就抓取那個cell裡面的數值（float）部分，當作value新增至某個dictionary

### 對整個dataframe跑過

In [7]:
#創造很多dict
names = locals()
for stock_nam in uni_names:
    names["dict_%s" % stock_nam] = {}

### 對於不同的stock，都把對應的period跟weight存成key跟value

In [17]:
uni_names

array(['A', 'ACT', 'ADP', 'AGN', 'AIG', 'AIV', 'ALEX', 'ALX', 'APD',
       'BEAM', 'BGP', 'BHC', 'BKS', 'BKW-OLD', 'BRK.B', 'C', 'CBY', 'CEN',
       'CMG', 'CP', 'CSG', 'CXW', 'DPS', 'EMC', 'FBHS', 'FDO', 'FO',
       'GGP', 'GLRE', 'GM', 'H', 'HHC', 'HLT', 'HME', 'JCP', 'LDG', 'LNY',
       'LOW', 'MA', 'MATX', 'MCD', 'MDLZ', 'NKE', 'NOMD', 'PAH', 'PG',
       'QSR', 'RTX', 'SBUX', 'SHLDQ', 'SKS', 'SPLS', 'TGT', 'V', 'WB-OLD',
       'WEN', 'YUM', 'ZTS'], dtype=object)

In [24]:
dict_H

{40: 4.35}

In [20]:
#assign dictionary
names = locals()
for stock_nam in uni_names:
    names["dict_%s" % stock_nam] = {}
    
    #前是row, 後是col
    for row in range(0, df.shape[0]):    
        for col in range(0, df.shape[1]):
            try: #因為可能碰到NaN
                if stock_nam == df.iloc[row][col].split()[0]: #如果stock_nam這個string在某個cell裡
                    testrow = df.iloc[row][col] #為了拿到數值部分
                    test_wei = testrow.split()[-3].split('%')
                    test_wei = test_wei[0][-5:]
                    try: #因為可能取到只有個位數的weight
                        test_wei = float(test_wei)
                    except: #那就退一位數
                        test_wei = test_wei[-4:]
                        test_wei = float(test_wei)

                    names["dict_%s" % stock_nam][row] = test_wei#把數值當作value新增至字典，這時key是所在的row
            except:
                continue

In [9]:
print(dict_ADP)

{2: 9.93, 3: 9.58, 4: 8.96, 5: 11.65, 6: 9.76, 7: 18.65, 8: 17.56, 9: 18.81, 10: 2.98, 36: 1.14, 37: 9.05, 38: 9.51, 40: 0.26, 41: 7.68, 42: 11.75}

In [25]:
dict_stock = [] #list of dictionaries
dict_stock_str = [] #list of dictionary names, are strings

for stock_nam in uni_names:
    dict_stock.append(names["dict_%s" % stock_nam]) #把dictionary存進list裡面
    dict_stock_str.append(stock_nam) #存的是字串名稱

#df_weight = pd.DataFrame(dict_stock) #相當於 pd.DataFrame([dict_1, dict_2]) 這樣的寫法
df_weight = pd.DataFrame.from_dict(dict_stock)
df_weight = df_weight.T #因為是by row的加進dataframe裡，所以要transpose

#rename columns
df_weight.columns = dict_stock_str

In [26]:
df_weight.head()

,A,ACT,ADP,AGN,AIG,AIV,ALEX,ALX,APD,BEAM,...,SBUX,SHLDQ,SKS,SPLS,TGT,V,WB-OLD,WEN,YUM,ZTS
0,4.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,9.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,9.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,8.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Rename row names as time period

In [27]:
rownames = df.index.tolist()

In [28]:
len(rownames)

51

In [29]:
#make a dict of row names
row_name_dict = {}
for i in range(0, len(rownames)):
    row_name_dict[i] = rownames[i]

In [30]:
df_weight = pd.DataFrame.rename(df_weight, index= row_name_dict)
df_weight.head()

,A,ACT,ADP,AGN,AIG,AIV,ALEX,ALX,APD,BEAM,...,SBUX,SHLDQ,SKS,SPLS,TGT,V,WB-OLD,WEN,YUM,ZTS
2019 Q4,4.23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,7.32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019 Q3,3.44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019 Q2,NaN,NaN,9.93,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.64,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2019 Q1,NaN,NaN,9.58,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,11.06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2018 Q4,NaN,NaN,8.96,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,12.71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Save File

In [31]:
df_weight.to_csv('weights.csv', index=True)